services:
     postgres:
        container_name: postgres
        image: postgres
        restart: always
        environment:
          POSTGRES_DB: CatalogDb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - "5433:5432"
        networks:
          - shopfinity
     
     redis:
        image: redis:7
        container_name: redis
        restart: always
        ports:
            - "6379:6379"
        networks: 
            - shopfinity
            
            
networks:
  shopfinity:
    name: shopfinity